name: Build
on: [pull_request, push]
jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
      - name: Build the app
        run: ./gradlew build
      - name: Release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "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"
          prerelease: true
          automatic_release_tag: "release"
          files: |
            *.apk
          
