name: Build
on: [pull_request, push]
jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
      - name: Build the app
        run: ./gradlew build
      - name: Automatic Releases
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.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 }}"
          prerelease: true
          files: |
            *.apk
          
